In [28]:
import numpy as np
import numpy.matlib as nm
from svgd import SVGD

class MVN:
    def __init__(self, mu, A):
        self.mu = mu
        self.A = A
    
    def dlnprob(self, theta):
        return -1 * np.matmul(theta - nm.repmat(self.mu, theta.shape[0], 1), self.A)
    
if __name__ == '__main__':
    A = np.array([[0.2260,0.1652],[0.1652,0.6779]])
    mu = np.array([-0.6871,0.8010])
    
    model = MVN(mu, A)
    
    # Note that the variance is underestimated when the number of draws is small, and that
    # at 500 draws inference is pretty slow.
    num_draws = 500
    x0 = np.random.normal(0,1, [num_draws,2]);
    A_var = np.diagonal(np.linalg.inv(A))
    theta = SVGD().update(x0, model.dlnprob, n_iter=1000, stepsize=0.01)
    
    print "ground truth: ", mu
    print "svgd: ", np.mean(theta, axis=0)

    print "ground truth variance: ", A_var
    print "svgd: ", np.var(theta, axis=0)


ground truth:  [-0.6871  0.801 ]
svgd:  [-0.68735551  0.80188102]
ground truth variance:  [ 5.38381802  1.79487074]
svgd:  [ 5.25306155  1.75764204]


In [18]:
A = np.array([[0.2260,0.1652],[0.1652,0.6779]])
mu = np.array([-0.6871,0.8010])
theta = np.array([1, 2])

foo = nm.repmat(mu, 2, 1)
print foo
print foo * A
print np.matmul(foo, A)

print np.matmul(theta - nm.repmat(mu, theta.shape[0], 1), A)

model = MVN(mu, A)
print model.dlnprob(theta)

[[-0.6871  0.801 ]
 [-0.6871  0.801 ]]
[[-0.1552846   0.1323252 ]
 [-0.11350892  0.5429979 ]]
[[-0.0229594   0.42948898]
 [-0.0229594   0.42948898]]
[[ 0.5793594   1.09151102]
 [ 0.5793594   1.09151102]]
[[-0.5793594  -1.09151102]
 [-0.5793594  -1.09151102]]
